from gym.spaces import Box, Dict, Tuple

SEED = 1
NUM_STEPS = 5
TESTING_ENV_SAMPLE_ACTION = 0

DISCRETE_VALUE = 1

BOX_LOW, BOX_HIGH, BOX_DIM = -5, 5, (10, 10)

NEW_BOX_DIM = (100, 1)
NEW_BOX_DIM_IMPOSSIBLE = (99,)

TESTING_BOX_OBSERVATION_SPACE = Box(BOX_LOW, BOX_HIGH, BOX_DIM)

TESTING_DICT_OBSERVATION_SPACE = Dict(
    key_1=Box(BOX_LOW, BOX_HIGH, BOX_DIM),
    key_2=Box(BOX_LOW, BOX_HIGH, BOX_DIM),
)

TESTING_NESTED_DICT_ACTION_SPACE = Dict(
    nested=Dict(nested=Box(BOX_LOW, BOX_HIGH, BOX_DIM))
)

TESTING_DOUBLY_NESTED_DICT_ACTION_SPACE = Dict(
    nested=Dict(nested=Dict(nested=Box(BOX_LOW, BOX_HIGH, BOX_DIM))),
)


TESTING_TUPLE_OBSERVATION_SPACE = Tuple(
    [Box(BOX_LOW, BOX_HIGH, BOX_DIM), Box(BOX_LOW, BOX_HIGH, BOX_DIM)]
)
